// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package keycloak

import (
	"context"

	"github.com/Nerzal/gocloak/v13"
	"github.com/go-resty/resty/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AddClientRolesToUser provides a mock function for the type MockClient
func (_mock *MockClient) AddClientRolesToUser(ctx context.Context, token string, realm string, idOfClient string, userID string, roles []gocloak.Role) error {
	ret := _mock.Called(ctx, token, realm, idOfClient, userID, roles)

	if len(ret) == 0 {
		panic("no return value specified for AddClientRolesToUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, []gocloak.Role) error); ok {
		r0 = returnFunc(ctx, token, realm, idOfClient, userID, roles)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_AddClientRolesToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddClientRolesToUser'
type MockClient_AddClientRolesToUser_Call struct {
	*mock.Call
}

// AddClientRolesToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - idOfClient string
//   - userID string
//   - roles []gocloak.Role
func (_e *MockClient_Expecter) AddClientRolesToUser(ctx any, token any, realm any, idOfClient any, userID any, roles any) *MockClient_AddClientRolesToUser_Call {
	return &MockClient_AddClientRolesToUser_Call{Call: _e.mock.On("AddClientRolesToUser", ctx, token, realm, idOfClient, userID, roles)}
}

func (_c *MockClient_AddClientRolesToUser_Call) Run(run func(ctx context.Context, token string, realm string, idOfClient string, userID string, roles []gocloak.Role)) *MockClient_AddClientRolesToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 []gocloak.Role
		if args[5] != nil {
			arg5 = args[5].([]gocloak.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_AddClientRolesToUser_Call) Return(err error) *MockClient_AddClientRolesToUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_AddClientRolesToUser_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, idOfClient string, userID string, roles []gocloak.Role) error) *MockClient_AddClientRolesToUser_Call {
	_c.Call.Return(run)
	return _c
}

// AddRealmRoleToUser provides a mock function for the type MockClient
func (_mock *MockClient) AddRealmRoleToUser(ctx context.Context, token string, realm string, userID string, roles []gocloak.Role) error {
	ret := _mock.Called(ctx, token, realm, userID, roles)

	if len(ret) == 0 {
		panic("no return value specified for AddRealmRoleToUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []gocloak.Role) error); ok {
		r0 = returnFunc(ctx, token, realm, userID, roles)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_AddRealmRoleToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRealmRoleToUser'
type MockClient_AddRealmRoleToUser_Call struct {
	*mock.Call
}

// AddRealmRoleToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - userID string
//   - roles []gocloak.Role
func (_e *MockClient_Expecter) AddRealmRoleToUser(ctx any, token any, realm any, userID any, roles any) *MockClient_AddRealmRoleToUser_Call {
	return &MockClient_AddRealmRoleToUser_Call{Call: _e.mock.On("AddRealmRoleToUser", ctx, token, realm, userID, roles)}
}

func (_c *MockClient_AddRealmRoleToUser_Call) Run(run func(ctx context.Context, token string, realm string, userID string, roles []gocloak.Role)) *MockClient_AddRealmRoleToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []gocloak.Role
		if args[4] != nil {
			arg4 = args[4].([]gocloak.Role)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_AddRealmRoleToUser_Call) Return(err error) *MockClient_AddRealmRoleToUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_AddRealmRoleToUser_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, userID string, roles []gocloak.Role) error) *MockClient_AddRealmRoleToUser_Call {
	_c.Call.Return(run)
	return _c
}

// AddUserToGroup provides a mock function for the type MockClient
func (_mock *MockClient) AddUserToGroup(ctx context.Context, token string, realm string, userID string, groupID string) error {
	ret := _mock.Called(ctx, token, realm, userID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, token, realm, userID, groupID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_AddUserToGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToGroup'
type MockClient_AddUserToGroup_Call struct {
	*mock.Call
}

// AddUserToGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - userID string
//   - groupID string
func (_e *MockClient_Expecter) AddUserToGroup(ctx any, token any, realm any, userID any, groupID any) *MockClient_AddUserToGroup_Call {
	return &MockClient_AddUserToGroup_Call{Call: _e.mock.On("AddUserToGroup", ctx, token, realm, userID, groupID)}
}

func (_c *MockClient_AddUserToGroup_Call) Run(run func(ctx context.Context, token string, realm string, userID string, groupID string)) *MockClient_AddUserToGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_AddUserToGroup_Call) Return(err error) *MockClient_AddUserToGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_AddUserToGroup_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, userID string, groupID string) error) *MockClient_AddUserToGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChildGroup provides a mock function for the type MockClient
func (_mock *MockClient) CreateChildGroup(ctx context.Context, token string, realm string, groupID string, group gocloak.Group) (string, error) {
	ret := _mock.Called(ctx, token, realm, groupID, group)

	if len(ret) == 0 {
		panic("no return value specified for CreateChildGroup")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, gocloak.Group) (string, error)); ok {
		return returnFunc(ctx, token, realm, groupID, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, gocloak.Group) string); ok {
		r0 = returnFunc(ctx, token, realm, groupID, group)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, gocloak.Group) error); ok {
		r1 = returnFunc(ctx, token, realm, groupID, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateChildGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChildGroup'
type MockClient_CreateChildGroup_Call struct {
	*mock.Call
}

// CreateChildGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - groupID string
//   - group gocloak.Group
func (_e *MockClient_Expecter) CreateChildGroup(ctx any, token any, realm any, groupID any, group any) *MockClient_CreateChildGroup_Call {
	return &MockClient_CreateChildGroup_Call{Call: _e.mock.On("CreateChildGroup", ctx, token, realm, groupID, group)}
}

func (_c *MockClient_CreateChildGroup_Call) Run(run func(ctx context.Context, token string, realm string, groupID string, group gocloak.Group)) *MockClient_CreateChildGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 gocloak.Group
		if args[4] != nil {
			arg4 = args[4].(gocloak.Group)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_CreateChildGroup_Call) Return(s string, err error) *MockClient_CreateChildGroup_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_CreateChildGroup_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, groupID string, group gocloak.Group) (string, error)) *MockClient_CreateChildGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateClient provides a mock function for the type MockClient
func (_mock *MockClient) CreateClient(context1 context.Context, s string, s1 string, client gocloak.Client) (string, error) {
	ret := _mock.Called(context1, s, s1, client)

	if len(ret) == 0 {
		panic("no return value specified for CreateClient")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.Client) (string, error)); ok {
		return returnFunc(context1, s, s1, client)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.Client) string); ok {
		r0 = returnFunc(context1, s, s1, client)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, gocloak.Client) error); ok {
		r1 = returnFunc(context1, s, s1, client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClient'
type MockClient_CreateClient_Call struct {
	*mock.Call
}

// CreateClient is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - client gocloak.Client
func (_e *MockClient_Expecter) CreateClient(context1 any, s any, s1 any, client any) *MockClient_CreateClient_Call {
	return &MockClient_CreateClient_Call{Call: _e.mock.On("CreateClient", context1, s, s1, client)}
}

func (_c *MockClient_CreateClient_Call) Run(run func(context1 context.Context, s string, s1 string, client gocloak.Client)) *MockClient_CreateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 gocloak.Client
		if args[3] != nil {
			arg3 = args[3].(gocloak.Client)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateClient_Call) Return(s2 string, err error) *MockClient_CreateClient_Call {
	_c.Call.Return(s2, err)
	return _c
}

func (_c *MockClient_CreateClient_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, client gocloak.Client) (string, error)) *MockClient_CreateClient_Call {
	_c.Call.Return(run)
	return _c
}

// CreateClientProtocolMapper provides a mock function for the type MockClient
func (_mock *MockClient) CreateClientProtocolMapper(context1 context.Context, s string, s1 string, s2 string, protocolMapperRepresentation gocloak.ProtocolMapperRepresentation) (string, error) {
	ret := _mock.Called(context1, s, s1, s2, protocolMapperRepresentation)

	if len(ret) == 0 {
		panic("no return value specified for CreateClientProtocolMapper")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, gocloak.ProtocolMapperRepresentation) (string, error)); ok {
		return returnFunc(context1, s, s1, s2, protocolMapperRepresentation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, gocloak.ProtocolMapperRepresentation) string); ok {
		r0 = returnFunc(context1, s, s1, s2, protocolMapperRepresentation)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, gocloak.ProtocolMapperRepresentation) error); ok {
		r1 = returnFunc(context1, s, s1, s2, protocolMapperRepresentation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateClientProtocolMapper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClientProtocolMapper'
type MockClient_CreateClientProtocolMapper_Call struct {
	*mock.Call
}

// CreateClientProtocolMapper is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
//   - protocolMapperRepresentation gocloak.ProtocolMapperRepresentation
func (_e *MockClient_Expecter) CreateClientProtocolMapper(context1 any, s any, s1 any, s2 any, protocolMapperRepresentation any) *MockClient_CreateClientProtocolMapper_Call {
	return &MockClient_CreateClientProtocolMapper_Call{Call: _e.mock.On("CreateClientProtocolMapper", context1, s, s1, s2, protocolMapperRepresentation)}
}

func (_c *MockClient_CreateClientProtocolMapper_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string, protocolMapperRepresentation gocloak.ProtocolMapperRepresentation)) *MockClient_CreateClientProtocolMapper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 gocloak.ProtocolMapperRepresentation
		if args[4] != nil {
			arg4 = args[4].(gocloak.ProtocolMapperRepresentation)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_CreateClientProtocolMapper_Call) Return(s3 string, err error) *MockClient_CreateClientProtocolMapper_Call {
	_c.Call.Return(s3, err)
	return _c
}

func (_c *MockClient_CreateClientProtocolMapper_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string, protocolMapperRepresentation gocloak.ProtocolMapperRepresentation) (string, error)) *MockClient_CreateClientProtocolMapper_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function for the type MockClient
func (_mock *MockClient) CreateGroup(ctx context.Context, token string, realm string, group gocloak.Group) (string, error) {
	ret := _mock.Called(ctx, token, realm, group)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.Group) (string, error)); ok {
		return returnFunc(ctx, token, realm, group)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.Group) string); ok {
		r0 = returnFunc(ctx, token, realm, group)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, gocloak.Group) error); ok {
		r1 = returnFunc(ctx, token, realm, group)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockClient_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - group gocloak.Group
func (_e *MockClient_Expecter) CreateGroup(ctx any, token any, realm any, group any) *MockClient_CreateGroup_Call {
	return &MockClient_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, token, realm, group)}
}

func (_c *MockClient_CreateGroup_Call) Run(run func(ctx context.Context, token string, realm string, group gocloak.Group)) *MockClient_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 gocloak.Group
		if args[3] != nil {
			arg3 = args[3].(gocloak.Group)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateGroup_Call) Return(s string, err error) *MockClient_CreateGroup_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClient_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, group gocloak.Group) (string, error)) *MockClient_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockClient
func (_mock *MockClient) CreateUser(context1 context.Context, s string, s1 string, user gocloak.User) (string, error) {
	ret := _mock.Called(context1, s, s1, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.User) (string, error)); ok {
		return returnFunc(context1, s, s1, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.User) string); ok {
		r0 = returnFunc(context1, s, s1, user)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, gocloak.User) error); ok {
		r1 = returnFunc(context1, s, s1, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - user gocloak.User
func (_e *MockClient_Expecter) CreateUser(context1 any, s any, s1 any, user any) *MockClient_CreateUser_Call {
	return &MockClient_CreateUser_Call{Call: _e.mock.On("CreateUser", context1, s, s1, user)}
}

func (_c *MockClient_CreateUser_Call) Run(run func(context1 context.Context, s string, s1 string, user gocloak.User)) *MockClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 gocloak.User
		if args[3] != nil {
			arg3 = args[3].(gocloak.User)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_CreateUser_Call) Return(s2 string, err error) *MockClient_CreateUser_Call {
	_c.Call.Return(s2, err)
	return _c
}

func (_c *MockClient_CreateUser_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, user gocloak.User) (string, error)) *MockClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockClient
func (_mock *MockClient) DeleteUser(context1 context.Context, s string, s1 string, s2 string) error {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockClient_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockClient_Expecter) DeleteUser(context1 any, s any, s1 any, s2 any) *MockClient_DeleteUser_Call {
	return &MockClient_DeleteUser_Call{Call: _e.mock.On("DeleteUser", context1, s, s1, s2)}
}

func (_c *MockClient_DeleteUser_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockClient_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_DeleteUser_Call) Return(err error) *MockClient_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteUser_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) error) *MockClient_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserFromGroup provides a mock function for the type MockClient
func (_mock *MockClient) DeleteUserFromGroup(ctx context.Context, token string, realm string, userID string, groupID string) error {
	ret := _mock.Called(ctx, token, realm, userID, groupID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserFromGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, token, realm, userID, groupID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteUserFromGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserFromGroup'
type MockClient_DeleteUserFromGroup_Call struct {
	*mock.Call
}

// DeleteUserFromGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - userID string
//   - groupID string
func (_e *MockClient_Expecter) DeleteUserFromGroup(ctx any, token any, realm any, userID any, groupID any) *MockClient_DeleteUserFromGroup_Call {
	return &MockClient_DeleteUserFromGroup_Call{Call: _e.mock.On("DeleteUserFromGroup", ctx, token, realm, userID, groupID)}
}

func (_c *MockClient_DeleteUserFromGroup_Call) Run(run func(ctx context.Context, token string, realm string, userID string, groupID string)) *MockClient_DeleteUserFromGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_DeleteUserFromGroup_Call) Return(err error) *MockClient_DeleteUserFromGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteUserFromGroup_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, userID string, groupID string) error) *MockClient_DeleteUserFromGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientRole provides a mock function for the type MockClient
func (_mock *MockClient) GetClientRole(ctx context.Context, token string, realm string, idOfClient string, roleName string) (*gocloak.Role, error) {
	ret := _mock.Called(ctx, token, realm, idOfClient, roleName)

	if len(ret) == 0 {
		panic("no return value specified for GetClientRole")
	}

	var r0 *gocloak.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*gocloak.Role, error)); ok {
		return returnFunc(ctx, token, realm, idOfClient, roleName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *gocloak.Role); ok {
		r0 = returnFunc(ctx, token, realm, idOfClient, roleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, token, realm, idOfClient, roleName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetClientRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientRole'
type MockClient_GetClientRole_Call struct {
	*mock.Call
}

// GetClientRole is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - idOfClient string
//   - roleName string
func (_e *MockClient_Expecter) GetClientRole(ctx any, token any, realm any, idOfClient any, roleName any) *MockClient_GetClientRole_Call {
	return &MockClient_GetClientRole_Call{Call: _e.mock.On("GetClientRole", ctx, token, realm, idOfClient, roleName)}
}

func (_c *MockClient_GetClientRole_Call) Run(run func(ctx context.Context, token string, realm string, idOfClient string, roleName string)) *MockClient_GetClientRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_GetClientRole_Call) Return(role *gocloak.Role, err error) *MockClient_GetClientRole_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockClient_GetClientRole_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, idOfClient string, roleName string) (*gocloak.Role, error)) *MockClient_GetClientRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientRolesByUserID provides a mock function for the type MockClient
func (_mock *MockClient) GetClientRolesByUserID(ctx context.Context, token string, realm string, idOfClient string, userID string) ([]*gocloak.Role, error) {
	ret := _mock.Called(ctx, token, realm, idOfClient, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetClientRolesByUserID")
	}

	var r0 []*gocloak.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) ([]*gocloak.Role, error)); ok {
		return returnFunc(ctx, token, realm, idOfClient, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) []*gocloak.Role); ok {
		r0 = returnFunc(ctx, token, realm, idOfClient, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gocloak.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, token, realm, idOfClient, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetClientRolesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientRolesByUserID'
type MockClient_GetClientRolesByUserID_Call struct {
	*mock.Call
}

// GetClientRolesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - idOfClient string
//   - userID string
func (_e *MockClient_Expecter) GetClientRolesByUserID(ctx any, token any, realm any, idOfClient any, userID any) *MockClient_GetClientRolesByUserID_Call {
	return &MockClient_GetClientRolesByUserID_Call{Call: _e.mock.On("GetClientRolesByUserID", ctx, token, realm, idOfClient, userID)}
}

func (_c *MockClient_GetClientRolesByUserID_Call) Run(run func(ctx context.Context, token string, realm string, idOfClient string, userID string)) *MockClient_GetClientRolesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_GetClientRolesByUserID_Call) Return(roles []*gocloak.Role, err error) *MockClient_GetClientRolesByUserID_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *MockClient_GetClientRolesByUserID_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, idOfClient string, userID string) ([]*gocloak.Role, error)) *MockClient_GetClientRolesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientSecret provides a mock function for the type MockClient
func (_mock *MockClient) GetClientSecret(ctx context.Context, token string, realm string, idOfClient string) (*gocloak.CredentialRepresentation, error) {
	ret := _mock.Called(ctx, token, realm, idOfClient)

	if len(ret) == 0 {
		panic("no return value specified for GetClientSecret")
	}

	var r0 *gocloak.CredentialRepresentation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*gocloak.CredentialRepresentation, error)); ok {
		return returnFunc(ctx, token, realm, idOfClient)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *gocloak.CredentialRepresentation); ok {
		r0 = returnFunc(ctx, token, realm, idOfClient)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.CredentialRepresentation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, token, realm, idOfClient)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetClientSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientSecret'
type MockClient_GetClientSecret_Call struct {
	*mock.Call
}

// GetClientSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - idOfClient string
func (_e *MockClient_Expecter) GetClientSecret(ctx any, token any, realm any, idOfClient any) *MockClient_GetClientSecret_Call {
	return &MockClient_GetClientSecret_Call{Call: _e.mock.On("GetClientSecret", ctx, token, realm, idOfClient)}
}

func (_c *MockClient_GetClientSecret_Call) Run(run func(ctx context.Context, token string, realm string, idOfClient string)) *MockClient_GetClientSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetClientSecret_Call) Return(credentialRepresentation *gocloak.CredentialRepresentation, err error) *MockClient_GetClientSecret_Call {
	_c.Call.Return(credentialRepresentation, err)
	return _c
}

func (_c *MockClient_GetClientSecret_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, idOfClient string) (*gocloak.CredentialRepresentation, error)) *MockClient_GetClientSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetClients provides a mock function for the type MockClient
func (_mock *MockClient) GetClients(context1 context.Context, s string, s1 string, getClientsParams gocloak.GetClientsParams) ([]*gocloak.Client, error) {
	ret := _mock.Called(context1, s, s1, getClientsParams)

	if len(ret) == 0 {
		panic("no return value specified for GetClients")
	}

	var r0 []*gocloak.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.GetClientsParams) ([]*gocloak.Client, error)); ok {
		return returnFunc(context1, s, s1, getClientsParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.GetClientsParams) []*gocloak.Client); ok {
		r0 = returnFunc(context1, s, s1, getClientsParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gocloak.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, gocloak.GetClientsParams) error); ok {
		r1 = returnFunc(context1, s, s1, getClientsParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClients'
type MockClient_GetClients_Call struct {
	*mock.Call
}

// GetClients is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - getClientsParams gocloak.GetClientsParams
func (_e *MockClient_Expecter) GetClients(context1 any, s any, s1 any, getClientsParams any) *MockClient_GetClients_Call {
	return &MockClient_GetClients_Call{Call: _e.mock.On("GetClients", context1, s, s1, getClientsParams)}
}

func (_c *MockClient_GetClients_Call) Run(run func(context1 context.Context, s string, s1 string, getClientsParams gocloak.GetClientsParams)) *MockClient_GetClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 gocloak.GetClientsParams
		if args[3] != nil {
			arg3 = args[3].(gocloak.GetClientsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetClients_Call) Return(clients []*gocloak.Client, err error) *MockClient_GetClients_Call {
	_c.Call.Return(clients, err)
	return _c
}

func (_c *MockClient_GetClients_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, getClientsParams gocloak.GetClientsParams) ([]*gocloak.Client, error)) *MockClient_GetClients_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponent provides a mock function for the type MockClient
func (_mock *MockClient) GetComponent(ctx context.Context, token string, realm string, componentID string) (*gocloak.Component, error) {
	ret := _mock.Called(ctx, token, realm, componentID)

	if len(ret) == 0 {
		panic("no return value specified for GetComponent")
	}

	var r0 *gocloak.Component
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*gocloak.Component, error)); ok {
		return returnFunc(ctx, token, realm, componentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *gocloak.Component); ok {
		r0 = returnFunc(ctx, token, realm, componentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.Component)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, token, realm, componentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponent'
type MockClient_GetComponent_Call struct {
	*mock.Call
}

// GetComponent is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - componentID string
func (_e *MockClient_Expecter) GetComponent(ctx any, token any, realm any, componentID any) *MockClient_GetComponent_Call {
	return &MockClient_GetComponent_Call{Call: _e.mock.On("GetComponent", ctx, token, realm, componentID)}
}

func (_c *MockClient_GetComponent_Call) Run(run func(ctx context.Context, token string, realm string, componentID string)) *MockClient_GetComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetComponent_Call) Return(component *gocloak.Component, err error) *MockClient_GetComponent_Call {
	_c.Call.Return(component, err)
	return _c
}

func (_c *MockClient_GetComponent_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, componentID string) (*gocloak.Component, error)) *MockClient_GetComponent_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroup provides a mock function for the type MockClient
func (_mock *MockClient) GetGroup(ctx context.Context, token string, realm string, groupID string) (*gocloak.Group, error) {
	ret := _mock.Called(ctx, token, realm, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroup")
	}

	var r0 *gocloak.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*gocloak.Group, error)); ok {
		return returnFunc(ctx, token, realm, groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *gocloak.Group); ok {
		r0 = returnFunc(ctx, token, realm, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, token, realm, groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroup'
type MockClient_GetGroup_Call struct {
	*mock.Call
}

// GetGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - groupID string
func (_e *MockClient_Expecter) GetGroup(ctx any, token any, realm any, groupID any) *MockClient_GetGroup_Call {
	return &MockClient_GetGroup_Call{Call: _e.mock.On("GetGroup", ctx, token, realm, groupID)}
}

func (_c *MockClient_GetGroup_Call) Run(run func(ctx context.Context, token string, realm string, groupID string)) *MockClient_GetGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetGroup_Call) Return(group *gocloak.Group, err error) *MockClient_GetGroup_Call {
	_c.Call.Return(group, err)
	return _c
}

func (_c *MockClient_GetGroup_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, groupID string) (*gocloak.Group, error)) *MockClient_GetGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroups provides a mock function for the type MockClient
func (_mock *MockClient) GetGroups(ctx context.Context, token string, realm string, params gocloak.GetGroupsParams) ([]*gocloak.Group, error) {
	ret := _mock.Called(ctx, token, realm, params)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 []*gocloak.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.GetGroupsParams) ([]*gocloak.Group, error)); ok {
		return returnFunc(ctx, token, realm, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.GetGroupsParams) []*gocloak.Group); ok {
		r0 = returnFunc(ctx, token, realm, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gocloak.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, gocloak.GetGroupsParams) error); ok {
		r1 = returnFunc(ctx, token, realm, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroups'
type MockClient_GetGroups_Call struct {
	*mock.Call
}

// GetGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - params gocloak.GetGroupsParams
func (_e *MockClient_Expecter) GetGroups(ctx any, token any, realm any, params any) *MockClient_GetGroups_Call {
	return &MockClient_GetGroups_Call{Call: _e.mock.On("GetGroups", ctx, token, realm, params)}
}

func (_c *MockClient_GetGroups_Call) Run(run func(ctx context.Context, token string, realm string, params gocloak.GetGroupsParams)) *MockClient_GetGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 gocloak.GetGroupsParams
		if args[3] != nil {
			arg3 = args[3].(gocloak.GetGroupsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetGroups_Call) Return(groups []*gocloak.Group, err error) *MockClient_GetGroups_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockClient_GetGroups_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, params gocloak.GetGroupsParams) ([]*gocloak.Group, error)) *MockClient_GetGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetRealmRole provides a mock function for the type MockClient
func (_mock *MockClient) GetRealmRole(ctx context.Context, token string, realm string, roleName string) (*gocloak.Role, error) {
	ret := _mock.Called(ctx, token, realm, roleName)

	if len(ret) == 0 {
		panic("no return value specified for GetRealmRole")
	}

	var r0 *gocloak.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*gocloak.Role, error)); ok {
		return returnFunc(ctx, token, realm, roleName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *gocloak.Role); ok {
		r0 = returnFunc(ctx, token, realm, roleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, token, realm, roleName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetRealmRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRealmRole'
type MockClient_GetRealmRole_Call struct {
	*mock.Call
}

// GetRealmRole is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - roleName string
func (_e *MockClient_Expecter) GetRealmRole(ctx any, token any, realm any, roleName any) *MockClient_GetRealmRole_Call {
	return &MockClient_GetRealmRole_Call{Call: _e.mock.On("GetRealmRole", ctx, token, realm, roleName)}
}

func (_c *MockClient_GetRealmRole_Call) Run(run func(ctx context.Context, token string, realm string, roleName string)) *MockClient_GetRealmRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetRealmRole_Call) Return(role *gocloak.Role, err error) *MockClient_GetRealmRole_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *MockClient_GetRealmRole_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, roleName string) (*gocloak.Role, error)) *MockClient_GetRealmRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserGroups provides a mock function for the type MockClient
func (_mock *MockClient) GetUserGroups(ctx context.Context, token string, realm string, userID string, params gocloak.GetGroupsParams) ([]*gocloak.Group, error) {
	ret := _mock.Called(ctx, token, realm, userID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGroups")
	}

	var r0 []*gocloak.Group
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, gocloak.GetGroupsParams) ([]*gocloak.Group, error)); ok {
		return returnFunc(ctx, token, realm, userID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, gocloak.GetGroupsParams) []*gocloak.Group); ok {
		r0 = returnFunc(ctx, token, realm, userID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gocloak.Group)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, gocloak.GetGroupsParams) error); ok {
		r1 = returnFunc(ctx, token, realm, userID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetUserGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGroups'
type MockClient_GetUserGroups_Call struct {
	*mock.Call
}

// GetUserGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - realm string
//   - userID string
//   - params gocloak.GetGroupsParams
func (_e *MockClient_Expecter) GetUserGroups(ctx any, token any, realm any, userID any, params any) *MockClient_GetUserGroups_Call {
	return &MockClient_GetUserGroups_Call{Call: _e.mock.On("GetUserGroups", ctx, token, realm, userID, params)}
}

func (_c *MockClient_GetUserGroups_Call) Run(run func(ctx context.Context, token string, realm string, userID string, params gocloak.GetGroupsParams)) *MockClient_GetUserGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 gocloak.GetGroupsParams
		if args[4] != nil {
			arg4 = args[4].(gocloak.GetGroupsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockClient_GetUserGroups_Call) Return(groups []*gocloak.Group, err error) *MockClient_GetUserGroups_Call {
	_c.Call.Return(groups, err)
	return _c
}

func (_c *MockClient_GetUserGroups_Call) RunAndReturn(run func(ctx context.Context, token string, realm string, userID string, params gocloak.GetGroupsParams) ([]*gocloak.Group, error)) *MockClient_GetUserGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function for the type MockClient
func (_mock *MockClient) GetUsers(context1 context.Context, s string, s1 string, getUsersParams gocloak.GetUsersParams) ([]*gocloak.User, error) {
	ret := _mock.Called(context1, s, s1, getUsersParams)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []*gocloak.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.GetUsersParams) ([]*gocloak.User, error)); ok {
		return returnFunc(context1, s, s1, getUsersParams)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.GetUsersParams) []*gocloak.User); ok {
		r0 = returnFunc(context1, s, s1, getUsersParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gocloak.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, gocloak.GetUsersParams) error); ok {
		r1 = returnFunc(context1, s, s1, getUsersParams)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockClient_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - getUsersParams gocloak.GetUsersParams
func (_e *MockClient_Expecter) GetUsers(context1 any, s any, s1 any, getUsersParams any) *MockClient_GetUsers_Call {
	return &MockClient_GetUsers_Call{Call: _e.mock.On("GetUsers", context1, s, s1, getUsersParams)}
}

func (_c *MockClient_GetUsers_Call) Run(run func(context1 context.Context, s string, s1 string, getUsersParams gocloak.GetUsersParams)) *MockClient_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 gocloak.GetUsersParams
		if args[3] != nil {
			arg3 = args[3].(gocloak.GetUsersParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_GetUsers_Call) Return(users []*gocloak.User, err error) *MockClient_GetUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockClient_GetUsers_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, getUsersParams gocloak.GetUsersParams) ([]*gocloak.User, error)) *MockClient_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockClient
func (_mock *MockClient) Login(context1 context.Context, s string, s1 string, s2 string, s3 string, s4 string) (*gocloak.JWT, error) {
	ret := _mock.Called(context1, s, s1, s2, s3, s4)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *gocloak.JWT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) (*gocloak.JWT, error)); ok {
		return returnFunc(context1, s, s1, s2, s3, s4)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) *gocloak.JWT); ok {
		r0 = returnFunc(context1, s, s1, s2, s3, s4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.JWT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string) error); ok {
		r1 = returnFunc(context1, s, s1, s2, s3, s4)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
//   - s3 string
//   - s4 string
func (_e *MockClient_Expecter) Login(context1 any, s any, s1 any, s2 any, s3 any, s4 any) *MockClient_Login_Call {
	return &MockClient_Login_Call{Call: _e.mock.On("Login", context1, s, s1, s2, s3, s4)}
}

func (_c *MockClient_Login_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string, s3 string, s4 string)) *MockClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_Login_Call) Return(jWT *gocloak.JWT, err error) *MockClient_Login_Call {
	_c.Call.Return(jWT, err)
	return _c
}

func (_c *MockClient_Login_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string, s3 string, s4 string) (*gocloak.JWT, error)) *MockClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// LoginAdmin provides a mock function for the type MockClient
func (_mock *MockClient) LoginAdmin(context1 context.Context, s string, s1 string, s2 string) (*gocloak.JWT, error) {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for LoginAdmin")
	}

	var r0 *gocloak.JWT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*gocloak.JWT, error)); ok {
		return returnFunc(context1, s, s1, s2)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *gocloak.JWT); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.JWT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(context1, s, s1, s2)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_LoginAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginAdmin'
type MockClient_LoginAdmin_Call struct {
	*mock.Call
}

// LoginAdmin is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockClient_Expecter) LoginAdmin(context1 any, s any, s1 any, s2 any) *MockClient_LoginAdmin_Call {
	return &MockClient_LoginAdmin_Call{Call: _e.mock.On("LoginAdmin", context1, s, s1, s2)}
}

func (_c *MockClient_LoginAdmin_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockClient_LoginAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_LoginAdmin_Call) Return(jWT *gocloak.JWT, err error) *MockClient_LoginAdmin_Call {
	_c.Call.Return(jWT, err)
	return _c
}

func (_c *MockClient_LoginAdmin_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) (*gocloak.JWT, error)) *MockClient_LoginAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutUserSession provides a mock function for the type MockClient
func (_mock *MockClient) LogoutUserSession(context1 context.Context, s string, s1 string, s2 string) error {
	ret := _mock.Called(context1, s, s1, s2)

	if len(ret) == 0 {
		panic("no return value specified for LogoutUserSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(context1, s, s1, s2)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_LogoutUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutUserSession'
type MockClient_LogoutUserSession_Call struct {
	*mock.Call
}

// LogoutUserSession is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
func (_e *MockClient_Expecter) LogoutUserSession(context1 any, s any, s1 any, s2 any) *MockClient_LogoutUserSession_Call {
	return &MockClient_LogoutUserSession_Call{Call: _e.mock.On("LogoutUserSession", context1, s, s1, s2)}
}

func (_c *MockClient_LogoutUserSession_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string)) *MockClient_LogoutUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_LogoutUserSession_Call) Return(err error) *MockClient_LogoutUserSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_LogoutUserSession_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string) error) *MockClient_LogoutUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// RestyClient provides a mock function for the type MockClient
func (_mock *MockClient) RestyClient() *resty.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RestyClient")
	}

	var r0 *resty.Client
	if returnFunc, ok := ret.Get(0).(func() *resty.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*resty.Client)
		}
	}
	return r0
}

// MockClient_RestyClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestyClient'
type MockClient_RestyClient_Call struct {
	*mock.Call
}

// RestyClient is a helper method to define mock.On call
func (_e *MockClient_Expecter) RestyClient() *MockClient_RestyClient_Call {
	return &MockClient_RestyClient_Call{Call: _e.mock.On("RestyClient")}
}

func (_c *MockClient_RestyClient_Call) Run(run func()) *MockClient_RestyClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_RestyClient_Call) Return(client *resty.Client) *MockClient_RestyClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockClient_RestyClient_Call) RunAndReturn(run func() *resty.Client) *MockClient_RestyClient_Call {
	_c.Call.Return(run)
	return _c
}

// SetPassword provides a mock function for the type MockClient
func (_mock *MockClient) SetPassword(context1 context.Context, s string, s1 string, s2 string, s3 string, b bool) error {
	ret := _mock.Called(context1, s, s1, s2, s3, b)

	if len(ret) == 0 {
		panic("no return value specified for SetPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, bool) error); ok {
		r0 = returnFunc(context1, s, s1, s2, s3, b)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_SetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPassword'
type MockClient_SetPassword_Call struct {
	*mock.Call
}

// SetPassword is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - s2 string
//   - s3 string
//   - b bool
func (_e *MockClient_Expecter) SetPassword(context1 any, s any, s1 any, s2 any, s3 any, b any) *MockClient_SetPassword_Call {
	return &MockClient_SetPassword_Call{Call: _e.mock.On("SetPassword", context1, s, s1, s2, s3, b)}
}

func (_c *MockClient_SetPassword_Call) Run(run func(context1 context.Context, s string, s1 string, s2 string, s3 string, b bool)) *MockClient_SetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockClient_SetPassword_Call) Return(err error) *MockClient_SetPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_SetPassword_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, s2 string, s3 string, b bool) error) *MockClient_SetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockClient
func (_mock *MockClient) UpdateUser(context1 context.Context, s string, s1 string, user gocloak.User) error {
	ret := _mock.Called(context1, s, s1, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, gocloak.User) error); ok {
		r0 = returnFunc(context1, s, s1, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockClient_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - s1 string
//   - user gocloak.User
func (_e *MockClient_Expecter) UpdateUser(context1 any, s any, s1 any, user any) *MockClient_UpdateUser_Call {
	return &MockClient_UpdateUser_Call{Call: _e.mock.On("UpdateUser", context1, s, s1, user)}
}

func (_c *MockClient_UpdateUser_Call) Run(run func(context1 context.Context, s string, s1 string, user gocloak.User)) *MockClient_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 gocloak.User
		if args[3] != nil {
			arg3 = args[3].(gocloak.User)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_UpdateUser_Call) Return(err error) *MockClient_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_UpdateUser_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, user gocloak.User) error) *MockClient_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
